#!/bin/bash

MODE=$1

. /etc/default/heads

if [ "$ENABLED" != "true" ]; then exit; fi

update_boot_signatures() {
  cd /boot
  find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
  DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
  echo $DEFAULT_FILES | xargs sha256sum > /boot/kexec_default_hashes.txt
  sha256sum `find /boot/kexec*.txt` | sudo -u ${LOCAL_USER} gpg --detach-sig | sudo cat > /boot/kexec.sig
}

CHANGED_FILES=$(cd /boot && /usr/bin/sha256sum -c kexec_hashes.txt | /bin/grep -v 'OK$' | cut -f1 -d ':')

# No changed files? No need to update signatures
if [ "$CHANGED_FILES" == "" -a "$MODE" != "force" ]; then exit; fi

if [ "$MODE" == "pre" ]; then
  if (zenity --question --title "ALERT: Pre-Update Changes in /boot detected!" --width 600 \
    --text "The following files in /boot were changed BEFORE the software update:\n\n$CHANGED_FILES\n\nThis could indicate a compromise! Click Abort to abort the software update and investigate, or Ignore to ignore the alert and continue." \
    --ok-label "Ignore" --cancel-label "Abort"); then
    exit 0
  else
    exit 1
  fi
fi

LAST_PACKAGE_CHANGE=$(egrep "^(Install|Remove):" /var/log/apt/history.log | tail -n1)
if (zenity --question --title "ALERT: Post-Update Changes in /boot detected!" --width 600 \
  --text "The following files in /boot have been changed:\n${CHANGED_FILES}\n\nThis is most likely caused by this software that just changed on your system:\n${LAST_PACKAGE_CHANGE}\n\nIf you suspect these packages changed the files, Select 'Update /boot signatures'.\n\nOtherwise this could indicate a compromise and you should click Cancel and investigate what has changed in /boot.\n\nNote that without updating your signatures the NEXT BOOT WILL FAIL!\n\nWould you like to update your signatures?" \
  --ok-label "Update /boot signatures" --cancel-label "Cancel"); then

  update_boot_signatures

  CHANGED_FILES=$(cd /boot && /usr/bin/sha256sum -c kexec_hashes.txt | /bin/grep -v 'OK$' | cut -f1 -d ':')

  if [ "$CHANGED_FILES" != "" ]; then
    zenity --error --title "File signatures not updated!" --width 600 \
      --text "The Following files do not have updated signatures:\n${CHANGED_FILES}\n\nResolve this issue before you reboot or Heads will refuse to boot!"
  elif ! sha256sum `find /boot/kexec*.txt` | sudo -u ${LOCAL_USER} gpg --verify /boot/kexec.sig - ; then
    zenity --error --title "GPG Signature failed!" --width 600 \
      --text "The GPG signature does not match! Signature update failed!\n\nResolve this issue before you reboot or Heads will refuse to boot!"
  else
    zenity --info --title "Signature update complete" --width 600 \
      --text "The signature update completed successfully. It's recommend that you reboot to verify the signatures from within Head itself."
  fi
fi
